name: Update Skello Calendars

on:
  schedule:
  - cron: "*/15 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Générer les calendriers
        run: python script.py

      - name: Commit et Push si changement
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add *.ics

          if git diff --cached --quiet; then
            echo "Aucun changement"
          else
            git commit -m "Mise à jour automatique des calendriers"
            git push
          fi